# Generated by Django 3.0.3 on 2020-04-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDoList_app', '0007_auto_20200401_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
